#!/usr/bin/env bash
# Installs, configures, and starts the server
# Imanol Asolo
sudo apt-get update
sudo apt-get install nginx
sudo uft "Nginx HTTP"
sudo nginx -t
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx reload
